# Use a multi-stage build to reduce the image size
# Stage 1: Build the application
FROM node:latest as builder

ENV NODE_ENV=development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --no-fund --no-audit --silent --prefer-offline

COPY . .

ENV NODE_CONFIG_DIR=/usr/src/app/config
ENV PISTEREO_CLIENT_BASE=/usr/src/app/dist/client

EXPOSE 3000

CMD [ "npm", "run", "start:dev"]
