/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Clock: typeof import('./components/Clock.vue')['default']
    CompactPlayer: typeof import('./components/CompactPlayer.vue')['default']
    Equaliser: typeof import('./components/Equaliser.vue')['default']
    MyProfile: typeof import('./components/MyProfile.vue')['default']
    MyProfileBanner: typeof import('./components/MyProfileBanner.vue')['default']
    NowPlaying: typeof import('./components/NowPlaying.vue')['default']
    NowPlayingRadio: typeof import('./components/NowPlayingRadio.vue')['default']
    Playlist: typeof import('./components/Playlist.vue')['default']
    Playlists: typeof import('./components/Playlists.vue')['default']
    RadioPlayer: typeof import('./components/RadioPlayer.vue')['default']
    RadioPresets: typeof import('./components/RadioPresets.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedAlbums: typeof import('./components/SavedAlbums.vue')['default']
    SavedShows: typeof import('./components/SavedShows.vue')['default']
    Search: typeof import('./components/Search.vue')['default']
    ShowChooser: typeof import('./components/ShowChooser.vue')['default']
    TopTracks: typeof import('./components/TopTracks.vue')['default']
    TrackInfo: typeof import('./components/TrackInfo.vue')['default']
  }
}
