/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AboutPage': RouteRecordInfo<'/AboutPage', '/AboutPage', Record<never, never>, Record<never, never>>,
    '/ExplorePage': RouteRecordInfo<'/ExplorePage', '/ExplorePage', Record<never, never>, Record<never, never>>,
    '/IndexPage': RouteRecordInfo<'/IndexPage', '/IndexPage', Record<never, never>, Record<never, never>>,
    '/LibraryPage': RouteRecordInfo<'/LibraryPage', '/LibraryPage', Record<never, never>, Record<never, never>>,
    '/NowPlayingPage': RouteRecordInfo<'/NowPlayingPage', '/NowPlayingPage', Record<never, never>, Record<never, never>>,
    '/PlaylistsPage': RouteRecordInfo<'/PlaylistsPage', '/PlaylistsPage', Record<never, never>, Record<never, never>>,
    '/ToolsPage': RouteRecordInfo<'/ToolsPage', '/ToolsPage', Record<never, never>, Record<never, never>>,
  }
}
