name: pistereo

services:
  pistereo-dev:
    dns:
      - 192.168.1.201
    build:
      context: .
      dockerfile: Dockerfile.production
    expose:
      - 3000
    environment:
      - HOST_IP=${HOST_IP} # export HOST_IP=$(hostname -I | awk '{print $1}')
      - TZ=Europe/London
    container_name: pistereo
    hostname: pistereo
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd:rw
    privileged: true
