/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MyProfile: typeof import('./components/MyProfile.vue')['default']
    MyProfileBanner: typeof import('./components/MyProfileBanner.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    Playlists: typeof import('./components/Playlists.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrackInfo: typeof import('./components/TrackInfo.vue')['default']
  }
}
