
name: pistereo

services:
  pistereo-librespot:
    dns:
      - 192.168.1.201
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    network_mode: host
    expose:
      - 3678
    volumes:
      - ./config:/app/config
      - ./socket:/app/socket
    container_name: pistereo-librespot
    hostname: pistereo-librespot
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd:rw
    privileged: true
